---
# tasks file for Cluster

- name: bypass ** MariaDB - zabbix - galera ** from firewalld
  shell: |
   firewall-cmd --zone=public --add-port=3306/tcp  --permanent
   firewall-cmd --zone=public --add-port=10050/tcp --permanent
   firewall-cmd --zone=public --add-port=3306/tcp --permanent
   firewall-cmd --zone=public --add-port=4567/tcp --permanent
   firewall-cmd --zone=public --add-port=4567/udp --permanent
   firewall-cmd --zone=public --add-port=4568/tcp --permanent
   firewall-cmd --zone=public --add-port=4568/udp --permanent
   firewall-cmd --zone=public --add-port=4444/tcp --permanent
   firewall-cmd --zone=public --add-port=4444/udp --permanent
   firewall-cmd --reload

- name: ------ Disabled selinux ------
  selinux: 
    state: disabled  
#- name: deploy MariaDB.repo
 # copy: src=MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo owner=root group=root mode=0644
#- name: import RPR-GPG-KEY-MariaDB
#  rpm_key: key=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB state=present

- name: --- Set host name ---
  shell: hostnamectl set-hostname {{ item }}
  with_items:
    - "{% for host in nodes %}{% if nodes[host].ssh == ansible_env.SSH_CONNECTION.split(' ')[2] %}{{ nodes[host].name }}{% endif %}{% endfor %}"   
  when: general_config.set_hostname 
    

- include_tasks: mysql.yml
  

- name: ----- install Tools Cluster ** rsysc,galera,socat,jemalloc **  -----
  yum: name={{ item }} state=present
  with_items:
    - rsync
    - galera
    - socat
    - jemalloc
  when:
    - master_node.ssh != ansible_env.SSH_CONNECTION.split(' ')[2]  

- name: ----- Stop MariaDB All server -----
  service: name=mariadb state=stopped  
  when:
    - master_node.ssh != ansible_env.SSH_CONNECTION.split(' ')[2]  

- name: ----- deploy server.conf to the servers -----
  template: src=primary-server.j2 dest=/etc/my.cnf.d/server.cnf
  when:
    - master_node.ssh != ansible_env.SSH_CONNECTION.split(' ')[2]  

- name: ----- run galera_new_cluster on the primary node -----
  shell: galera_new_cluster
  when:  
    - nodes.{{general_config.primary_node}}.ssh == ansible_env.SSH_CONNECTION.split(' ')[2] 
    - master_node.ssh != ansible_env.SSH_CONNECTION.split(' ')[2]  

- name: ----- start and enable mysqld (Nonprimary) -----
  service: name=mariadb state=started enabled=yes
  when:  
    - nodes.{{general_config.primary_node}}.ssh != ansible_env.SSH_CONNECTION.split(' ')[2] 
    - master_node.ssh != ansible_env.SSH_CONNECTION.split(' ')[2]
  
- include_tasks: zabbix-agent.yml
  when: zabbix_config.zabbix_install

- name: -- Start Config Mastre-slave --
  include_tasks: main-master-slave.yml  
  when: general_config.Master_slave

- name: --- install and config Monit Tools ---
  include_tasks: monit.yml
  when: general_config.monit_install  
