---
# task file for mysql
- name: ----- MySQL | Ensure mariadb packages are installed -----
  yum: name={{ item }} state="present"
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-common
    - MySQL-python

- name: ----- MySQL | Ensure mariadb is running and configured to start at boot -----
  service: name=mariadb state=started enabled=yes


- name: ----- MySQL | Change root user password on first run, this will only succeed (and only needs to succeed) on first playbook run -----
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_config.mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  
  with_items:
    - "{% for host in nodes %}{% if nodes[host].ssh == ansible_env.SSH_CONNECTION.split(' ')[2] %}{{ nodes[host].name }}{% endif %}{% endfor %}"   
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: MySQL | Ensure the anonymous mysql user ""@{{ansible_hostname}} is deleted
  mysql_user: user="" host="{{ ansible_hostname }}" state="absent" login_user=root login_password={{ mysql_config.mysql_root_password }}

- name: MySQL | Ensure the anonymous mysql user ""@localhost is deleted
  mysql_user: user="" state="absent" login_user=root login_password={{ mysql_config.mysql_root_password }}

- name: MySQL | Ensure the mysql test database is deleted
  mysql_db: db=test state=absent login_user=root login_password={{ mysql_config.mysql_root_password }}

  