---
# task file for mysql
# Create useranme and password for using Macro 
- name: "MySQL | Create database user"
  mysql_user: "name={{ zabiix_config.dbuser_macro_800item }}
              password={{ zabiix_config.dbpassword_macro_800item }}
              priv=*.*:ALL
              state=present
              login_user=root
              login_password={{ mysql_config.mysql_root_password }}"
  